/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardImportRouteImport } from './routes/dashboard/import'
import { Route as DashboardDiscoverRouteImport } from './routes/dashboard/discover'
import { Route as DashboardQuestionsIndexRouteImport } from './routes/dashboard/questions/index'
import { Route as DashboardJobsIndexRouteImport } from './routes/dashboard/jobs/index'
import { Route as DashboardInterviewIndexRouteImport } from './routes/dashboard/interview/index'
import { Route as DashboardEmailSyncIndexRouteImport } from './routes/dashboard/email-sync/index'
import { Route as DashboardCandidatesIndexRouteImport } from './routes/dashboard/candidates/index'
import { Route as DashboardAdminUserIndexRouteImport } from './routes/dashboard/admin-user/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as DashboardJobsAddRouteImport } from './routes/dashboard/jobs/add'
import { Route as DashboardJobsIdRouteImport } from './routes/dashboard/jobs/$id'
import { Route as DashboardInterviewIdRouteImport } from './routes/dashboard/interview/$id'
import { Route as DashboardCandidatesAddRouteImport } from './routes/dashboard/candidates/add'
import { Route as DashboardCandidatesIdRouteImport } from './routes/dashboard/candidates/$id'
import { Route as DashboardJobsIdIndexRouteImport } from './routes/dashboard/jobs/$id.index'
import { Route as DashboardJobsIdEditRouteImport } from './routes/dashboard/jobs/$id.edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardQuestionsIndexRoute = DashboardQuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInterviewIndexRoute = DashboardInterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailSyncIndexRoute = DashboardEmailSyncIndexRouteImport.update({
  id: '/email-sync/',
  path: '/email-sync/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCandidatesIndexRoute =
  DashboardCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdminUserIndexRoute = DashboardAdminUserIndexRouteImport.update({
  id: '/admin-user/',
  path: '/admin-user/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardJobsAddRoute = DashboardJobsAddRouteImport.update({
  id: '/jobs/add',
  path: '/jobs/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsIdRoute = DashboardJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInterviewIdRoute = DashboardInterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCandidatesAddRoute = DashboardCandidatesAddRouteImport.update({
  id: '/candidates/add',
  path: '/candidates/add',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCandidatesIdRoute = DashboardCandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsIdIndexRoute = DashboardJobsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardJobsIdRoute,
} as any)
const DashboardJobsIdEditRoute = DashboardJobsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardJobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/candidates/$id': typeof DashboardCandidatesIdRoute
  '/dashboard/candidates/add': typeof DashboardCandidatesAddRoute
  '/dashboard/interview/$id': typeof DashboardInterviewIdRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRouteWithChildren
  '/dashboard/jobs/add': typeof DashboardJobsAddRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/dashboard/admin-user/': typeof DashboardAdminUserIndexRoute
  '/dashboard/candidates/': typeof DashboardCandidatesIndexRoute
  '/dashboard/email-sync/': typeof DashboardEmailSyncIndexRoute
  '/dashboard/interview/': typeof DashboardInterviewIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/questions/': typeof DashboardQuestionsIndexRoute
  '/dashboard/jobs/$id/edit': typeof DashboardJobsIdEditRoute
  '/dashboard/jobs/$id/': typeof DashboardJobsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/candidates/$id': typeof DashboardCandidatesIdRoute
  '/dashboard/candidates/add': typeof DashboardCandidatesAddRoute
  '/dashboard/interview/$id': typeof DashboardInterviewIdRoute
  '/dashboard/jobs/add': typeof DashboardJobsAddRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/dashboard/admin-user': typeof DashboardAdminUserIndexRoute
  '/dashboard/candidates': typeof DashboardCandidatesIndexRoute
  '/dashboard/email-sync': typeof DashboardEmailSyncIndexRoute
  '/dashboard/interview': typeof DashboardInterviewIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/questions': typeof DashboardQuestionsIndexRoute
  '/dashboard/jobs/$id/edit': typeof DashboardJobsIdEditRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/candidates/$id': typeof DashboardCandidatesIdRoute
  '/dashboard/candidates/add': typeof DashboardCandidatesAddRoute
  '/dashboard/interview/$id': typeof DashboardInterviewIdRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRouteWithChildren
  '/dashboard/jobs/add': typeof DashboardJobsAddRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/dashboard/admin-user/': typeof DashboardAdminUserIndexRoute
  '/dashboard/candidates/': typeof DashboardCandidatesIndexRoute
  '/dashboard/email-sync/': typeof DashboardEmailSyncIndexRoute
  '/dashboard/interview/': typeof DashboardInterviewIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/questions/': typeof DashboardQuestionsIndexRoute
  '/dashboard/jobs/$id/edit': typeof DashboardJobsIdEditRoute
  '/dashboard/jobs/$id/': typeof DashboardJobsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/'
    | '/dashboard/candidates/$id'
    | '/dashboard/candidates/add'
    | '/dashboard/interview/$id'
    | '/dashboard/jobs/$id'
    | '/dashboard/jobs/add'
    | '/login/'
    | '/signup/'
    | '/dashboard/admin-user/'
    | '/dashboard/candidates/'
    | '/dashboard/email-sync/'
    | '/dashboard/interview/'
    | '/dashboard/jobs/'
    | '/dashboard/questions/'
    | '/dashboard/jobs/$id/edit'
    | '/dashboard/jobs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard'
    | '/dashboard/candidates/$id'
    | '/dashboard/candidates/add'
    | '/dashboard/interview/$id'
    | '/dashboard/jobs/add'
    | '/login'
    | '/signup'
    | '/dashboard/admin-user'
    | '/dashboard/candidates'
    | '/dashboard/email-sync'
    | '/dashboard/interview'
    | '/dashboard/jobs'
    | '/dashboard/questions'
    | '/dashboard/jobs/$id/edit'
    | '/dashboard/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/'
    | '/dashboard/candidates/$id'
    | '/dashboard/candidates/add'
    | '/dashboard/interview/$id'
    | '/dashboard/jobs/$id'
    | '/dashboard/jobs/add'
    | '/_auth/login/'
    | '/_auth/signup/'
    | '/dashboard/admin-user/'
    | '/dashboard/candidates/'
    | '/dashboard/email-sync/'
    | '/dashboard/interview/'
    | '/dashboard/jobs/'
    | '/dashboard/questions/'
    | '/dashboard/jobs/$id/edit'
    | '/dashboard/jobs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/discover': {
      id: '/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/questions/': {
      id: '/dashboard/questions/'
      path: '/questions'
      fullPath: '/dashboard/questions/'
      preLoaderRoute: typeof DashboardQuestionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/jobs'
      fullPath: '/dashboard/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/interview/': {
      id: '/dashboard/interview/'
      path: '/interview'
      fullPath: '/dashboard/interview/'
      preLoaderRoute: typeof DashboardInterviewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email-sync/': {
      id: '/dashboard/email-sync/'
      path: '/email-sync'
      fullPath: '/dashboard/email-sync/'
      preLoaderRoute: typeof DashboardEmailSyncIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/candidates/': {
      id: '/dashboard/candidates/'
      path: '/candidates'
      fullPath: '/dashboard/candidates/'
      preLoaderRoute: typeof DashboardCandidatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin-user/': {
      id: '/dashboard/admin-user/'
      path: '/admin-user'
      fullPath: '/dashboard/admin-user/'
      preLoaderRoute: typeof DashboardAdminUserIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/jobs/add': {
      id: '/dashboard/jobs/add'
      path: '/jobs/add'
      fullPath: '/dashboard/jobs/add'
      preLoaderRoute: typeof DashboardJobsAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/$id': {
      id: '/dashboard/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/dashboard/jobs/$id'
      preLoaderRoute: typeof DashboardJobsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/interview/$id': {
      id: '/dashboard/interview/$id'
      path: '/interview/$id'
      fullPath: '/dashboard/interview/$id'
      preLoaderRoute: typeof DashboardInterviewIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/candidates/add': {
      id: '/dashboard/candidates/add'
      path: '/candidates/add'
      fullPath: '/dashboard/candidates/add'
      preLoaderRoute: typeof DashboardCandidatesAddRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/candidates/$id': {
      id: '/dashboard/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/dashboard/candidates/$id'
      preLoaderRoute: typeof DashboardCandidatesIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/$id/': {
      id: '/dashboard/jobs/$id/'
      path: '/'
      fullPath: '/dashboard/jobs/$id/'
      preLoaderRoute: typeof DashboardJobsIdIndexRouteImport
      parentRoute: typeof DashboardJobsIdRoute
    }
    '/dashboard/jobs/$id/edit': {
      id: '/dashboard/jobs/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/jobs/$id/edit'
      preLoaderRoute: typeof DashboardJobsIdEditRouteImport
      parentRoute: typeof DashboardJobsIdRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardJobsIdRouteChildren {
  DashboardJobsIdEditRoute: typeof DashboardJobsIdEditRoute
  DashboardJobsIdIndexRoute: typeof DashboardJobsIdIndexRoute
}

const DashboardJobsIdRouteChildren: DashboardJobsIdRouteChildren = {
  DashboardJobsIdEditRoute: DashboardJobsIdEditRoute,
  DashboardJobsIdIndexRoute: DashboardJobsIdIndexRoute,
}

const DashboardJobsIdRouteWithChildren = DashboardJobsIdRoute._addFileChildren(
  DashboardJobsIdRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardDiscoverRoute: typeof DashboardDiscoverRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCandidatesIdRoute: typeof DashboardCandidatesIdRoute
  DashboardCandidatesAddRoute: typeof DashboardCandidatesAddRoute
  DashboardInterviewIdRoute: typeof DashboardInterviewIdRoute
  DashboardJobsIdRoute: typeof DashboardJobsIdRouteWithChildren
  DashboardJobsAddRoute: typeof DashboardJobsAddRoute
  DashboardAdminUserIndexRoute: typeof DashboardAdminUserIndexRoute
  DashboardCandidatesIndexRoute: typeof DashboardCandidatesIndexRoute
  DashboardEmailSyncIndexRoute: typeof DashboardEmailSyncIndexRoute
  DashboardInterviewIndexRoute: typeof DashboardInterviewIndexRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
  DashboardQuestionsIndexRoute: typeof DashboardQuestionsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDiscoverRoute: DashboardDiscoverRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCandidatesIdRoute: DashboardCandidatesIdRoute,
  DashboardCandidatesAddRoute: DashboardCandidatesAddRoute,
  DashboardInterviewIdRoute: DashboardInterviewIdRoute,
  DashboardJobsIdRoute: DashboardJobsIdRouteWithChildren,
  DashboardJobsAddRoute: DashboardJobsAddRoute,
  DashboardAdminUserIndexRoute: DashboardAdminUserIndexRoute,
  DashboardCandidatesIndexRoute: DashboardCandidatesIndexRoute,
  DashboardEmailSyncIndexRoute: DashboardEmailSyncIndexRoute,
  DashboardInterviewIndexRoute: DashboardInterviewIndexRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
  DashboardQuestionsIndexRoute: DashboardQuestionsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
