/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardInterviewRouteImport } from './routes/dashboard/interview'
import { Route as DashboardImportRouteImport } from './routes/dashboard/import'
import { Route as DashboardDiscoverRouteImport } from './routes/dashboard/discover'
import { Route as DashboardAudioInterviewRouteImport } from './routes/dashboard/audio-interview'
import { Route as DashboardJobsIndexRouteImport } from './routes/dashboard/jobs/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as DashboardJobsIdRouteImport } from './routes/dashboard/jobs/$id'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInterviewRoute = DashboardInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDiscoverRoute = DashboardDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAudioInterviewRoute = DashboardAudioInterviewRouteImport.update({
  id: '/audio-interview',
  path: '/audio-interview',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardJobsIdRoute = DashboardJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/audio-interview': typeof DashboardAudioInterviewRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/interview': typeof DashboardInterviewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/audio-interview': typeof DashboardAudioInterviewRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/interview': typeof DashboardInterviewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/audio-interview': typeof DashboardAudioInterviewRoute
  '/dashboard/discover': typeof DashboardDiscoverRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/interview': typeof DashboardInterviewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/audio-interview'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/interview'
    | '/dashboard/'
    | '/dashboard/jobs/$id'
    | '/login/'
    | '/signup/'
    | '/dashboard/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/audio-interview'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/interview'
    | '/dashboard'
    | '/dashboard/jobs/$id'
    | '/login'
    | '/signup'
    | '/dashboard/jobs'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/dashboard/audio-interview'
    | '/dashboard/discover'
    | '/dashboard/import'
    | '/dashboard/interview'
    | '/dashboard/'
    | '/dashboard/jobs/$id'
    | '/_auth/login/'
    | '/_auth/signup/'
    | '/dashboard/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/interview': {
      id: '/dashboard/interview'
      path: '/interview'
      fullPath: '/dashboard/interview'
      preLoaderRoute: typeof DashboardInterviewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/discover': {
      id: '/dashboard/discover'
      path: '/discover'
      fullPath: '/dashboard/discover'
      preLoaderRoute: typeof DashboardDiscoverRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/audio-interview': {
      id: '/dashboard/audio-interview'
      path: '/audio-interview'
      fullPath: '/dashboard/audio-interview'
      preLoaderRoute: typeof DashboardAudioInterviewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/jobs'
      fullPath: '/dashboard/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/jobs/$id': {
      id: '/dashboard/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/dashboard/jobs/$id'
      preLoaderRoute: typeof DashboardJobsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAudioInterviewRoute: typeof DashboardAudioInterviewRoute
  DashboardDiscoverRoute: typeof DashboardDiscoverRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardInterviewRoute: typeof DashboardInterviewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardJobsIdRoute: typeof DashboardJobsIdRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAudioInterviewRoute: DashboardAudioInterviewRoute,
  DashboardDiscoverRoute: DashboardDiscoverRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardInterviewRoute: DashboardInterviewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardJobsIdRoute: DashboardJobsIdRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
